name: Build and Deploy APK to S3

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v3

    - name: Build APK using Gradle
      run: |
        ./gradlew assembleRelease

    - name: Upload APK to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        # No args field needed anymore
        SOURCE_DIR: './app/build/outputs/apk/release'
        DEST_DIR: 's3://apkbucket1/android-apks/'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Replace with your region
        AWS_S3_BUCKET: 'apkbucket1'  # Make sure the bucket name is correct
